{"name": "Проверка авторизации пользователем с неверным логином", "status": "passed", "start": 1720555322225, "stop": 1720555322529, "uuid": "9f1fb61b-9a9f-47b5-9d86-ecdd411051a6", "historyId": "33bd82cd61948aaa98ba19c712291dda", "testCaseId": "33bd82cd61948aaa98ba19c712291dda", "fullName": "tests.test_user_authentication.TestLoginUser#test_login_user_incorrect_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "2940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}