{"name": "Проверка авторизации пользователем с неверным логином", "status": "passed", "start": 1719860991395, "stop": 1719860991745, "uuid": "191c43fb-02eb-4698-b03b-e406ee0a958f", "historyId": "33bd82cd61948aaa98ba19c712291dda", "testCaseId": "33bd82cd61948aaa98ba19c712291dda", "fullName": "tests.test_user_authentication.TestLoginUser#test_login_user_incorrect_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-6FRR489"}, {"name": "thread", "value": "17592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}